name: logger_flutter_ns_v1
description: A simple plug & play flutter logger console. You can use this plugin for logging on ide or by shaking your phone to see logs on phone.
version: 1.0.2
homepage: https://github.com/mehmetarsay/logger_flutter_ns

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  logger: ^2.6.1
  path_provider: ^2.0.15
  share_plus: ^11.1.0
  sensors_plus: ^6.1.2
dev_dependencies:
  test: ^1.26.3